apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keyvaluestores.myk8s.local
spec:
  group: myk8s.local
  names:
    kind: keyvaluestore
    plural: keyvaluestores
    singular: keyvaluestore
    shortNames:
      - kv
    categories:
      - custom
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: integer